# Generated by Django 4.2.7 on 2024-07-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description_address',
            field=models.CharField(max_length=600, verbose_name=' Краткое описание проблемы и адрес'),
        ),
    ]
