# Generated by Django 4.2.7 on 2024-04-22 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options_remove_products_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='cotent',
        ),
        migrations.AddField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Статус'),
        ),
    ]
