# Generated by Django 4.2.7 on 2024-04-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_rename_description_products_cotent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cotent',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
